#!/bin/sh

$LAMBDA_TASK_ROOT/jre17-slim/bin/java \
    --add-opens java.base/java.util=ALL-UNNAMED \
    -XX:+TieredCompilation \
    -XX:TieredStopAtLevel=1 \
    -Xshare:on \
    -XX:MaxHeapSize=445645k \
    -XX:MaxMetaspaceSize=52429k \
    -XX:ReservedCodeCacheSize=26214k \
    -XX:+UseSerialGC \
    -jar function.jar "$_HANDLER"
